# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: wwang.work@gmail.com
author_name: wwang
has_ai_rules: false
has_binder: true
has_settings: true
kind: frontend-and-server
labextension_name: jvox-lab-ext-screenreader
project_short_description: A JupyterLab extension for JVox for screen reading
python_name: jvox_lab_ext_screenreader
repository: https:github.com/ProgrammingEduBVI/JupyterVox.git
test: true

